/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hehe;

/**
 *
 * @author ABC
 */
import java.sql.*;
import javax.swing.JOptionPane;
public class book1 extends javax.swing.JFrame {

    /**
     * Creates new form book1
     */
    public book1() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        movie = new javax.swing.JComboBox();
        refresh = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        date = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        quantity = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        movie.setBackground(new java.awt.Color(153, 153, 255));
        movie.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        movie.setForeground(new java.awt.Color(0, 0, 102));
        movie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "             --------", "Badlapur", "PK", "Batman vs Superman", "Avengers - Age of Ultron", "Gone Girl", "Argo", "Boyhood", "Interstellar", "Star Wars- 7", "Gabbar", "Reservoir Dogs", "Psycho", "Inception", "Jurassic Park World", "Snatch" }));
        movie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieActionPerformed(evt);
            }
        });
        jPanel1.add(movie, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 160, 30));

        refresh.setBackground(new java.awt.Color(153, 153, 255));
        refresh.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        refresh.setForeground(new java.awt.Color(0, 0, 102));
        refresh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "         --------", "Samosa", "Coke", "Butter Popcorn", "Nachos", "Tea/Coffee" }));
        jPanel1.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 120, 30));

        jLabel1.setFont(new java.awt.Font("Andy", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("Movie -");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 120, -1));

        jLabel3.setFont(new java.awt.Font("Andy", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 0));
        jLabel3.setText("Date -");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, -1, -1));

        jLabel2.setFont(new java.awt.Font("Andy", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("Refreshments- ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        jLabel5.setFont(new java.awt.Font("Andy", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 0));
        jLabel5.setText("Quantity -");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, -1, -1));

        submit.setBackground(new java.awt.Color(153, 153, 255));
        submit.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        submit.setForeground(new java.awt.Color(153, 0, 102));
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 550, -1, -1));

        date.setBackground(new java.awt.Color(153, 153, 255));
        date.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        date.setForeground(new java.awt.Color(0, 0, 102));
        date.setText("YYYY/MM/DD");
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 120, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\ABC\\Desktop\\movie1\\src\\hehe\\Bookmyshow.jpg")); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 470, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\ABC\\Desktop\\movie1\\src\\hehe\\Guardians-of-the-Galaxy-2-1308x1940.jpg")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, -40, 450, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\ABC\\Desktop\\movie1\\src\\hehe\\Yo.jpg")); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 630));

        quantity.setBackground(new java.awt.Color(153, 153, 255));
        quantity.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        quantity.setForeground(new java.awt.Color(0, 0, 102));
        quantity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "    -----", "   1", "   2", "   3", "   4", "   5", "   6" }));
        jPanel1.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 80, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 630));

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));

        jLabel4.setText("item quantity");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
   // String mov_arr[]={"Badlapur","PK","Batman vs Superman","Avengers-Age of Ultron","Gone Girl"};
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
       String m=movie.getSelectedItem().toString();String mov=null;String scr=null;String the=null;String my=null;int count=0;
       String d=date.getText().toString();String item=null;
       String r=refresh.getSelectedItem().toString();
       String q=quantity.getSelectedItem().toString();
       if(m.equals("")||d.equals("")||r.equals("")||q.equals("")){
          JOptionPane.showMessageDialog(this,"Please Enter All The Fields"); 
       }
       else{
        try{
           Class.forName("java.sql.Driver");
           Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/pmoviebook","anirudh","anirudh");
           Statement st=conn.createStatement();
           Statement st1=conn.createStatement();
           String query4="select booking_id from booking";
           ResultSet rs3=st.executeQuery(query4);
           while(rs3.next()){
               my=rs3.getString("booking_id");
               count++;
           }
           //count=(Integer.parseInt(my))+1;
           String query1="select movie_id from movie where movie_name ='"+m+"';";
           ResultSet rs=st.executeQuery(query1);
           if(rs.first()){
               mov=rs.getString("movie_id");
               
           }
           String query2="select screen_no,theater_id from screen where movie_id='"+mov+"';";
           ResultSet rs1=st1.executeQuery(query2);
           if(rs1.first()){
               scr=rs1.getString("screen_no");
               the=rs1.getString("theater_id");
           }
           String query5="select item_id from refreshments where item_name='"+r+"';";
           
           ResultSet rs5=st.executeQuery(query5);
           if(rs5.first()){
               item=rs5.getString("item_id");
           }
           String query="insert into booking values('"+(count+1)+"','"+cid+"','"+the+"','"+scr+"','"+d+"','"+q+"');";
           
           
          st.executeUpdate(query);
           String query6="insert into booking_refreshments values('"+(count+1)+"','"+item+"','"+1+"');";
           
           st.executeUpdate(query6);
           //System.out.println(query5);
           
           
           JOptionPane.showMessageDialog(this,"Your Booking has been Done. Unique Booking-Id is = "+(count+1));
           rs.close();
           rs1.close();
           st.close();
           st1.close();
           conn.close();
           
           
           
           
       }
        
       catch(SQLException e){
           e.printStackTrace();
           JOptionPane.showMessageDialog(this,"Error in connectivity");
       }
       catch(Exception e) {
           e.printStackTrace();
           JOptionPane.showMessageDialog(this,"Something Went Wrong");
       }
        TicketBook t = new TicketBook();
           t.setVisible(true);
           dispose();


       }
    }//GEN-LAST:event_submitActionPerformed

    private void movieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movieActionPerformed

    /**
     * @param args the command line arguments
     */String cid=null;
    public void function(String s){
        cid=s;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(book1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(book1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(book1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(book1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new book1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField date;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox movie;
    private javax.swing.JComboBox quantity;
    private javax.swing.JComboBox refresh;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
